import { 
  Info, ShieldAlert, PlayCircle, ListChecks, Activity, 
  ShieldCheck, HelpCircle, AlertTriangle, FileText, Scissors, Clock, User
} from 'lucide-react';
import PageHeader from '../components/PageHeader';

function InfoSection({ title, icon: Icon, color, children }) {
  return (
    <div className="card card-premium pop-in" style={{ padding: 24, borderRadius: 24, border: `1.5px solid ${color}40`, boxShadow: `0 10px 20px ${color}08`, background: '#fff' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <Icon size={20} style={{ color }} />
        <span style={{ fontSize: '0.75rem', fontWeight: 800, color: 'var(--text-muted)', letterSpacing: '0.05em' }}>{title.toUpperCase()}</span>
      </div>
      {children}
    </div>
  );
}

function UsageStep({ number, title, text }) {
  return (
    <div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
      <div style={{ width: 24, height: 24, borderRadius: '50%', background: 'var(--teal)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.75rem', fontWeight: 800, flexShrink: 0 }}>
        {number}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div style={{ fontWeight: 700, fontSize: '0.95rem' }}>{title}</div>
        <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>{text}</div>
      </div>
    </div>
  );
}

function RiskFactorRow({ icon: Icon, title, details }) {
  return (
    <div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
      <Icon size={18} style={{ color: 'var(--primary)', flexShrink: 0, marginTop: 2 }} />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <div style={{ fontWeight: 700, fontSize: '0.9rem' }}>{title}</div>
        <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{details}</div>
      </div>
    </div>
  );
}

function ScoreLevelRow({ label, range, color }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 16px', background: `${color}08`, borderRadius: 12, marginBottom: 8 }}>
      <span style={{ fontSize: '0.9rem', fontWeight: 600 }}>{label}</span>
      <span style={{ fontSize: '0.9rem', fontWeight: 800, color }}>{range}</span>
    </div>
  );
}

export default function AppInfoPage() {
  return (
    <div className="animate-in">
      <PageHeader title="APP INFORMATION" backPath="/home" showProfile />

      <div className="container" style={{ padding: '24px 20px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 24, paddingBottom: 80 }}>
          
          {/* Medical Disclaimer */}
          <InfoSection title="Medical Disclaimer" icon={AlertTriangle} color="#F44336">
            <p style={{ fontSize: '0.9rem', fontWeight: 600, color: '#D32F2F', lineHeight: 1.6 }}>
              This application is designed for informational purposes only and is intended for use by healthcare professionals. It does not provide medical advice, diagnosis, or treatment. It is NOT a substitute for professional clinical judgment. Always consult a qualified physician or healthcare provider before making any medical decisions based on the risk scores generated by this app.
            </p>
          </InfoSection>

          {/* Overview */}
          <InfoSection title="Overview" icon={FileText} color="var(--primary)">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <div style={{ fontSize: '1.1rem', fontWeight: 800 }}>Postoperative Pulmonary Complications (POPC)</div>
              <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                PPCs are a major cause of postoperative morbidity and increased hospital stay. This app uses evidence-based risk assessment models to predict risk and guide management.
              </p>
            </div>
          </InfoSection>

          {/* Getting Started */}
          <InfoSection title="Getting Started" icon={PlayCircle} color="var(--teal)">
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              <UsageStep number="1" title="Patient Enrollment" text="Register a patient using their unique hospital ID. Ensure demographics are accurate." />
              <UsageStep number="2" title="Comprehensive Survey" text="Complete all sections from Medical History to Intraoperative factors." />
              <UsageStep number="3" title="Risk Stratification" text="The app calculates a point-based score instantly." />
              <UsageStep number="4" title="Clinical Action" text="Review the management advice tailored to the patient's risk category." />
            </div>
          </InfoSection>

          {/* Risk Factors */}
          <InfoSection title="Risk Factor Breakdown" icon={ListChecks} color="#9C27B0">
            <RiskFactorRow icon={User} title="Patient Factors" details="Age > 50, Preoperative SpO2 < 96%, Recent respiratory infection, Anemia (Hb < 10g/dL)." />
            <RiskFactorRow icon={Scissors} title="Surgical Factors" details="Intrathoracic or Upper Abdominal surgery, Surgery duration > 2 hours, Emergency status." />
            <RiskFactorRow icon={Clock} title="Clinical History" details="Chronic Lung Disease (COPD/Asthma), Smoking status, Congestive Heart Failure." />
          </InfoSection>

          {/* Scoring System */}
          <InfoSection title="The Scoring System" icon={Activity} color="#FF9800">
            <p style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: 16 }}>Risk categories based on simplified ARISCAT methodology:</p>
            <ScoreLevelRow label="Low Risk" range="0 - 30 points" color="#4CAF50" />
            <ScoreLevelRow label="Moderate Risk" range="31 - 45 points" color="#FFC107" />
            <ScoreLevelRow label="High Risk" range="46 - 60 points" color="#FF9800" />
            <ScoreLevelRow label="Very High" range="> 60 points" color="#F44336" />
            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontStyle: 'italic', marginTop: 12 }}>
              Higher scores indicate an increased likelihood of pneumonia, respiratory failure, or prolonged intubation.
            </p>
          </InfoSection>

          {/* FAQ */}
          <InfoSection title="FAQ" icon={HelpCircle} color="#757575">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
              <div>
                <div style={{ fontWeight: 800, fontSize: '0.95rem', marginBottom: 4 }}>Is the score a definitive diagnosis?</div>
                <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>No, the score is a risk stratification tool. Clinical judgment and patient-specific context should always be prioritized.</div>
              </div>
              <div>
                <div style={{ fontWeight: 800, fontSize: '0.95rem', marginBottom: 4 }}>How does the app handle emergency surgeries?</div>
                <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>Emergency status is a significant risk factor. Selecting this option adds specific points to the total score.</div>
              </div>
            </div>
          </InfoSection>

          <div style={{ textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.8rem', marginTop: 24 }}>
            POPC Portal Web v2.0.1 • Clinical Protocol v4.2 • &copy; 2026
          </div>
        </div>
      </div>
    </div>
  );
}

