import SwiftUI

struct AppInfoView: View {
    @Environment(\.presentationMode) var presentationMode
    
    var body: some View {
        VStack(spacing: 0) {
            // Header
            Theme.primaryGradient
            .overlay(
                HStack {
                    Button(action: { NotificationCenter.default.post(name: NSNotification.Name("GoHomeNotification"), object: nil) }) {
                        Image(systemName: "chevron.left")
                            .font(.title3.bold())
                            .foregroundColor(.white)
                            .padding(10)
                            .background(Circle().fill(Color.white.opacity(0.2)))
                    }
                    Spacer()
                    Text("App Information")
                        .font(.headline.bold())
                        .foregroundColor(.white)
                    Spacer()
                    Color.clear.frame(width: 40, height: 40)
                }
                .padding()
            )
            .frame(height: 110)

            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 24) {
                    
                    // Medical Disclaimer (REQUIRED BY APPLE)
                    InfoSection(title: "Medical Disclaimer", icon: "exclamationmark.triangle.fill", color: Theme.categoryRed) {
                        VStack(alignment: .leading, spacing: 10) {
                            Text("This application is designed for informational purposes only and is intended for use by healthcare professionals. It does not provide medical advice, diagnosis, or treatment. It is NOT a substitute for professional clinical judgment. Always consult a qualified physician or healthcare provider before making any medical decisions based on the risk scores generated by this app.")
                                .font(.system(size: 14, weight: .medium))
                                .foregroundColor(Theme.categoryRed)
                        }
                    }

                    // App Purpose Card
                    InfoSection(title: "Overview", icon: "doc.text.magnifyingglass", color: Theme.appPrimary) {
                        VStack(alignment: .leading, spacing: 10) {
                            Text("Postoperative Pulmonary Complications (POPC)")
                                .font(.headline)
                            Text("PPCs are a major cause of postoperative morbidity and increased hospital stay. This app uses evidence-based risk assessment models to predict risk and guide management.")
                                .font(.system(size: 15))
                                .foregroundColor(.secondary)
                        }
                    }

                    // How to Use Step-by-Step
                    InfoSection(title: "Getting Started", icon: "play.circle.fill", color: Theme.appTeal) {
                        VStack(alignment: .leading, spacing: 12) {
                            UsageStep(number: "1", title: "Patient Enrollment", text: "Register a patient using their unique hospital ID. Ensure demographics are accurate.")
                            UsageStep(number: "2", title: "Comprehensive Survey", text: "Complete all sections from Medical History to Intraoperative factors.")
                            UsageStep(number: "3", title: "Risk Stratification", text: "The app calculates a point-based score instantly.")
                            UsageStep(number: "4", title: "Clinical Action", text: "Review the management advice tailored to the patient's risk category.")
                        }
                    }

                    // Detailed Risk Factors
                    InfoSection(title: "Risk Factor Breakdown", icon: "list.bullet.indent", color: .purple) {
                        VStack(alignment: .leading, spacing: 14) {
                            RiskFactorRow(icon: "person.fill", title: "Patient Factors", details: "Age > 50, Preoperative SpO2 < 96%, Recent respiratory infection, Anemia (Hb < 10g/dL).")
                            RiskFactorRow(icon: "scissors", title: "Surgical Factors", details: "Intrathoracic or Upper Abdominal surgery, Surgery duration > 2 hours, Emergency status.")
                            RiskFactorRow(icon: "clock.fill", title: "Clinical History", details: "Chronic Lung Disease (COPD/Asthma), Smoking status, Congestive Heart Failure.")
                        }
                    }

                    // Scoring System Detailed
                    InfoSection(title: "The Scoring System", icon: "chart.bar.fill", color: .orange) {
                        VStack(alignment: .leading, spacing: 14) {
                            Text("Risk categories based on simplified ARISCAT methodology:")
                                .font(.system(size: 14, weight: .semibold))
                            
                            VStack(spacing: 8) {
                                ScoreLevelRow(label: "Low Risk", range: "0 - 30points", color: .green)
                                ScoreLevelRow(label: "Moderate Risk", range: "31 - 45 points", color: .yellow)
                                ScoreLevelRow(label: "High Risk", range: "46 - 60 points", color: .orange)
                                ScoreLevelRow(label: "Very High", range: "> 60 points", color: .red)
                            }
                            
                            Text("Higher scores indicate an increased likelihood of pneumonia, respiratory failure, or prolonged intubation.")
                                .font(.caption)
                                .foregroundColor(.secondary)
                                .italic()
                        }
                    }
                    
                    // Prevention Strategies
                    InfoSection(title: "PPC Prevention Tips", icon: "shield.fill", color: .green) {
                        VStack(alignment: .leading, spacing: 10) {
                            BulletPoint(text: "Encourage early mobilization and lung expansion exercises.")
                            BulletPoint(text: "Optimize preoperative comorbidities (Smoking cessation > 4 weeks).")
                            BulletPoint(text: "Utilize lung-protective ventilation during surgery.")
                            BulletPoint(text: "Postoperative incentive spirometry for high-risk cases.")
                        }
                    }

                    // FAQ Section
                    InfoSection(title: "FAQ", icon: "questionmark.circle.fill", color: .gray) {
                        VStack(alignment: .leading, spacing: 14) {
                            FAQRow(q: "What if I don't have all preoperative data?", a: "The score might be incomplete. It's recommended to gather as much data as possible for an accurate risk assessment.")
                            FAQRow(q: "How does the app handle emergency surgeries?", a: "Emergency status is a significant risk factor. Selecting this option adds specific points to the total score to account for increased risk.")
                            FAQRow(q: "Can I save a survey and return later?", a: "Yes, you can track pending surveys in the 'Pending' section on your dashboard.")
                            FAQRow(q: "Is the score a definitive diagnosis?", a: "No, the score is a risk stratification tool. Clinical judgment and patient-specific context should always be prioritized.")
                            FAQRow(q: "How often should I update the assessment?", a: "A new assessment should be done if the surgical plan or the patient's clinical condition changes significantly.")
                            FAQRow(q: "How can I update my profile details?", a: "Tap the profile icon on the home screen to view your information or use the Settings page to update credentials.")
                        }
                    }

                    Spacer(minLength: 40)
                }
                .padding(.horizontal)
            }
        }
        .popupAppear()
        .animatedBackground()
        .navigationBarHidden(true)
    }
}

// Helper Components
struct InfoSection<Content: View>: View {
    let title: String
    let icon: String
    let color: Color
    let content: () -> Content
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(spacing: 12) {
                Image(systemName: icon)
                    .foregroundColor(color)
                    .font(.title3.bold())
                Text(title.uppercased())
                    .font(.caption.bold())
                    .foregroundColor(.gray)
            }
            
            content()
        }
        .padding(20)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .fill(Color.white)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .stroke(color.opacity(0.4), lineWidth: 1.5)
        )
        .shadow(color: color.opacity(0.15), radius: 10, x: 0, y: 5)
    }
}

struct UsageStep: View {
    let number: String
    let title: String
    let text: String
    
    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Text(number)
                .font(.system(size: 12, weight: .bold))
                .foregroundColor(.white)
                .frame(width: 22, height: 22)
                .background(Circle().fill(Theme.appTeal))
                .padding(.top, 2)
            
            VStack(alignment: .leading, spacing: 4) {
                Text(title)
                    .font(.system(size: 15, weight: .bold))
                Text(text)
                    .font(.system(size: 14))
                    .foregroundColor(.secondary)
            }
        }
    }
}

struct RiskFactorRow: View {
    let icon: String
    let title: String
    let details: String
    
    var body: some View {
        HStack(alignment: .top, spacing: 14) {
            Image(systemName: icon)
                .foregroundColor(Theme.appPrimary)
                .frame(width: 20)
            
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.system(size: 14, weight: .bold))
                Text(details)
                    .font(.system(size: 13))
                    .foregroundColor(.secondary)
            }
        }
    }
}

struct ScoreLevelRow: View {
    let label: String
    let range: String
    let color: Color
    
    var body: some View {
        HStack {
            Text(label)
                .font(.system(size: 13, weight: .medium))
            Spacer()
            Text(range)
                .font(.system(size: 13, weight: .bold))
                .foregroundColor(color)
        }
        .padding(10)
        .background(color.opacity(0.08))
        .cornerRadius(10)
    }
}

struct BulletPoint: View {
    let text: String
    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            Text("•")
                .foregroundColor(Theme.appPrimary)
                .bold()
            Text(text)
                .font(.system(size: 14))
                .foregroundColor(.secondary)
        }
    }
}

struct FAQRow: View {
    let q: String
    let a: String
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(q)
                .font(.system(size: 14, weight: .bold))
                .foregroundColor(.primary)
            Text(a)
                .font(.system(size: 13))
                .foregroundColor(.secondary)
        }
    }
}

#Preview {
    AppInfoView()
}
